resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/nsls2-collection-2021-2.0
      endpoint: github

jobs:
  - template: collection-2021-1.2.yml@templates
    parameters:
      beamline_acronym: ISS
  - template: nsls2-collection-2021-2.1.yml@templates
    parameters:
      beamline_acronym: ISS
